### ISSUE TITLE
how use pswp.getCurrentIndex() and pswp.goTo(index) of photoswipe in react-photoswipe

### ISSUE THREAD

**Issue by linjieAda** [minhtranite/react-photoswipe#15]
if I want to  use  pswp.getCurrentIndex() and pswp.goTo(index), how should I do ?

**Comment by dlbnco** [comment]
Did you find it out?

**Comment by ilionic** [comment]
@linjieAda is it closed because you found solution?

**Comment by eseQ** [comment]
@dalbinaco use `before/afterChange`:
```javascript
afterChange = (item) => {
  this.element = item;
}
...
if (this.element) this.element.goTo();
```
`before/afterChange` will be called on open gallery too.
